/**
 * Authoring for design-harness variants: write a new fixture that derives from
 * an existing one by swapping handlebars templates and appending CSS, then
 * render it with render_fixture like any other.
 *
 * Safety is structural, not a gate. The caller supplies DATA only — template
 * source (handlebars), CSS, a few scalar overrides. The fixture's JavaScript is
 * generated here from a fixed template with every caller value passed through
 * JSON.stringify, so no caller-written code ever reaches the node process that
 * renders it. Writes stay under <module>/tools/design-harness/, never replace a
 * file this module did not generate, and refuse symlinks.
 */
import { existsSync, lstatSync, mkdirSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

export const GENERATED_MARKER = "// generated by foundry-mcp-live write_variant";
const MAX_BYTES = 200_000;
const MAX_TEMPLATES = 20;

const NAME = /^[A-Za-z0-9][\w-]*$/;
const TEMPLATE_KEY = /^(?!.*\.\.)[\w.-]+(?:\/[\w.-]+)*\.hbs$/;

const harnessRoot = (moduleDir) => path.join(moduleDir, "tools", "design-harness");

function inside(parent, child) {
  const rel = path.relative(parent, child);
  return rel !== "" && !rel.startsWith("..") && !path.isAbsolute(rel);
}

function refuseSymlink(p) {
  try { if (lstatSync(p).isSymbolicLink()) return `refusing to write through a symlink: ${p}`; } catch { /* does not exist yet */ }
  return null;
}

/** Template paths a fixture mentions, following sibling fixture imports a few levels. */
export function scanTemplates(fixturesDir, fixture, depth = 3, seen = new Set()) {
  const found = new Set();
  if (depth < 0 || seen.has(fixture)) return found;
  seen.add(fixture);
  let src;
  try { src = readFileSync(path.join(fixturesDir, `${fixture}.mjs`), "utf8"); } catch { return found; }
  for (const m of src.matchAll(/["'`]((?:[\w.-]+\/)*[\w.-]+\.hbs)["'`]/g)) found.add(m[1]);
  for (const m of src.matchAll(/from\s+["']\.\/([\w-]+)\.mjs["']/g)) {
    for (const t of scanTemplates(fixturesDir, m[1], depth - 1, seen)) found.add(t);
  }
  return found;
}

function validate({ name, base, templates, css, title, width, classes }) {
  if (!NAME.test(name ?? "")) return "`name` must be letters, digits, `-` or `_`, starting with a letter or digit.";
  if (!NAME.test(base ?? "")) return "`base` must name an existing fixture (letters, digits, `-`, `_`).";
  if (name === base) return "`name` must differ from `base`.";
  const keys = Object.keys(templates ?? {});
  if (keys.length > MAX_TEMPLATES) return `at most ${MAX_TEMPLATES} templates per variant (got ${keys.length}).`;
  const bases = new Set();
  for (const k of keys) {
    if (!TEMPLATE_KEY.test(k)) return `template key \`${k}\` must be a relative .hbs path as the base fixture names it (e.g. templates/x.hbs), with no \`..\`.`;
    const b = path.basename(k);
    if (bases.has(b)) return `two template keys share the file name \`${b}\`; rename one.`;
    bases.add(b);
    if (typeof templates[k] !== "string" || Buffer.byteLength(templates[k]) > MAX_BYTES) return `template \`${k}\` must be a string under ${MAX_BYTES} bytes.`;
  }
  if (css !== undefined && (typeof css !== "string" || Buffer.byteLength(css) > MAX_BYTES)) return `css must be a string under ${MAX_BYTES} bytes.`;
  if (title !== undefined && typeof title !== "string") return "title must be a string.";
  if (width !== undefined && !(Number.isInteger(width) && width > 0 && width < 5000)) return "width must be a positive integer under 5000.";
  if (classes !== undefined && !(Array.isArray(classes) && classes.every((c) => /^[\w-]+$/.test(c)))) return "classes must be an array of CSS class names.";
  if (!keys.length && !css && title === undefined && width === undefined && classes === undefined) {
    return "nothing to vary: pass `templates`, `css`, `title`, `width` or `classes`.";
  }
  return null;
}

function fixtureSource({ name, base, templateMap, css, title, width, classes }) {
  const overrides = {};
  if (title !== undefined) overrides.title = title;
  if (width !== undefined) overrides.width = width;
  if (classes !== undefined) overrides.classes = classes;
  return `${GENERATED_MARKER} — safe to delete; the tool never overwrites a fixture without this line.
// Variant "${name}" of "${base}". Template swaps and CSS are data written by the tool; edit them freely.
import base from "./${base}.mjs";

const TEMPLATES = ${JSON.stringify(templateMap, null, 2)};
const CSS = ${JSON.stringify(css ?? "")};
const OVERRIDES = ${JSON.stringify(overrides)};

const swap = (w) => {
  const t = (x) => TEMPLATES[x] ?? x;
  const out = { ...w };
  if (w.template) out.template = t(w.template);
  if (w.parts) out.parts = w.parts.map((p) => ({ ...p, template: t(p.template) }));
  out.css = (w.css ?? "") + "\\n" + CSS;
  return { ...out, ...OVERRIDES };
};

export default {
  ...swap(base),
  ...(base.build ? { build: (state) => swap(base.build(state)) } : {}),
};
`;
}

/**
 * Write (or overwrite our own) variant fixture.
 * @returns {{error:string}|{fixtureFile:string,templateFiles:string[],unmatched:string[],known:string[]}}
 */
export function writeVariant(moduleDir, args) {
  const bad = validate(args);
  if (bad) return { error: bad };
  const { name, base, templates = {}, css, title, width, classes } = args;
  const root = harnessRoot(moduleDir), fixturesDir = path.join(root, "fixtures");
  if (!existsSync(path.join(fixturesDir, `${base}.mjs`))) return { error: `no base fixture \`${base}\` in ${fixturesDir}.` };

  const fixtureFile = path.join(fixturesDir, `${name}.mjs`);
  const variantDir = path.join(root, "variants", name);
  for (const p of [fixtureFile, variantDir]) {
    if (!inside(root, p)) return { error: `refusing to write outside ${root}.` };
    const link = refuseSymlink(p) ?? refuseSymlink(path.dirname(p));
    if (link) return { error: link };
  }
  if (!inside(realpathSync(root), realpathSync(fixturesDir))) return { error: `${fixturesDir} resolves outside ${root}.` };
  if (existsSync(fixtureFile) && !readFileSync(fixtureFile, "utf8").startsWith(GENERATED_MARKER)) {
    return { error: `\`${name}\` is a hand-written fixture; this tool only overwrites variants it generated. Pick another name.` };
  }

  const templateMap = {}, templateFiles = [];
  mkdirSync(fixturesDir, { recursive: true });
  if (Object.keys(templates).length) mkdirSync(variantDir, { recursive: true });
  for (const [key, source] of Object.entries(templates)) {
    const file = path.join(variantDir, path.basename(key));
    if (refuseSymlink(file)) return { error: refuseSymlink(file) };
    writeFileSync(file, source);
    templateMap[key] = path.relative(moduleDir, file).split(path.sep).join("/"); // renderWindow reads MODULE-relative
    templateFiles.push(file);
  }
  writeFileSync(fixtureFile, fixtureSource({ name, base, templateMap, css, title, width, classes }));

  const known = [...scanTemplates(fixturesDir, base)];
  return { fixtureFile, templateFiles, known, unmatched: Object.keys(templates).filter((k) => !known.includes(k)) };
}

/** Remove a variant this module generated (its fixture and variants/<name>/); anything else is refused. */
export function discardVariant(moduleDir, name) {
  if (!NAME.test(name ?? "")) return { error: "`name` must be letters, digits, `-` or `_`." };
  const root = harnessRoot(moduleDir);
  const fixtureFile = path.join(root, "fixtures", `${name}.mjs`), variantDir = path.join(root, "variants", name);
  if (!existsSync(fixtureFile)) return { error: `no fixture \`${name}\` in ${path.dirname(fixtureFile)}.` };
  if (!readFileSync(fixtureFile, "utf8").startsWith(GENERATED_MARKER)) {
    return { error: `\`${name}\` was not generated by write_variant; refusing to delete a hand-written fixture.` };
  }
  for (const p of [fixtureFile, variantDir]) {
    if (!inside(root, p)) return { error: `refusing to delete outside ${root}.` };
    const link = refuseSymlink(p);
    if (link) return { error: link };
  }
  rmSync(fixtureFile);
  const hadDir = existsSync(variantDir);
  if (hadDir) rmSync(variantDir, { recursive: true });
  return { removed: [fixtureFile, ...(hadDir ? [variantDir] : [])] };
}
